import {
  readFileSync,
  writeFileSync,
} from 'fs';
import { join } from 'path';
import findLastIndex from 'lodash.findlastindex';
import { spawn } from 'child_process';

export function setupProxy(): string {
  const proxyFile = join('src', 'setupProxy.js');
  const proxyCode = `/*
 * This file was auto-generated by ShiftJS.
 *
 * It is used to mock the calls to the backend when developing locally.
 * Please keep it with your source control tool.
 * Please do not remove or change it manually.
 */
const { setupProxy } = require('@binaris/shift-local-proxy');
module.exports = setupProxy(__dirname);
`;
  writeFileSync(proxyFile, proxyCode, { flag: 'wx' });
  return `Created ${proxyFile}, please commit this file`;
}

export function installPackages(): Promise<string> {
  return new Promise((resolve, reject) => {
    const dependencies = [
      '@binaris/shift-local-proxy',
      '@binaris/shift-babel-macro',
      '@binaris/shift-fetch-runtime',
      '@binaris/shift-db',
    ];
    const args = [
      'install',
      '--save',
      '--loglevel',
      'error',
    ].concat(dependencies);
    const child = spawn('npm', args, { stdio: 'inherit' });
    child.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`Could not install ${dependencies.join(' ')}`));
        return;
      }
      resolve(`Packages installed
Modified package.json, please commit this file`);
    });
  });
}

export function ignoreShift(): string {
  const gitIgnoreFile = '.gitignore';
  const ignorePattern = '.shift*';
  let initialContent;
  try {
    initialContent = readFileSync(gitIgnoreFile, { encoding: 'utf8' });
  } catch (e) {
    return `Did not update ${gitIgnoreFile}`;
  }
  const lines: string[] = initialContent.split('\n');
  const found = lines.find((line) => line === ignorePattern);
  if (found) {
    return `Did not need to update ${gitIgnoreFile}`;
  }
  const lastIndex = findLastIndex(lines, (line: string) => !!line.trim ().length ) || 0;
  lines.splice(lastIndex + 1, 0, ignorePattern);
  const newContent = lines.join('\n');
  writeFileSync(gitIgnoreFile, newContent);
  return `Updated ${gitIgnoreFile}, please commit this file`;
}
