#!/bin/bash
set -euo pipefail

(cd interfaces/ &&
     npm install --no-package-lock &&
     npm run generate-koa-server && npm run generate-node-client)

# Might not work if file already has "scripts" entry.
function addScripts {
    cp $1 $1.bk
    jq  '. + { scripts: ((["lint", "test"] | map( { (.) : "echo generated code" } ) | add) + { build: "tsc" }) }' < $1.bk > $1
}

addScripts gen-server/package.json
addScripts gen-client/package.json
